version: '3'
services:
  postgres:
    image: postgres:13
    container_name: scan-immo-db
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  postgres-test:
    image: postgres:13
    container_name: scan-immo-test-db
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
